---
title: "Guide to the pbdADIOS Package"
author: "Drew Schmidt"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: true
    toc: true
    number_sections: true
    css: include/custom.css
    highlight: kate
bibliography: include/pbdADIOS.bib
csl: "include/ieee.csl"
vignette: >
  %\VignetteIndexEntry{Guide to the pbdADIOS Package}
  %\VignetteEngine{knitr::rmarkdown}
---

# Introduction

The **pbdADIOS** package is part of the pbdR project for high performance statistical computing [[@pbdR2012]].



## Installation

Installation requires the **pbdMPI** package [[@Chen2012pbdMPIpackage]].  You can find more details in the corresponding package vignette [[@Chen2012pbdMPIvignette]].


```{bash, echo=TRUE, eval=FALSE}
R CMD INSTALL pbdADIOS_0.1-0.tar.gz --configure-args="--with-adios-home=/path/to/adios"
```





# Legal

&copy; 2016 Alan Smithee.

Permission is granted to make and distribute verbatim copies of this vignette and its source provided the copyright notice and this permission notice are preserved on all copies.

Work for the **pbdADIOS** package is supported in part by ...

Any opinions, findings, and conclusions or recommendations expressed in  this material are those of the authors and do not necessarily reflect the  views of the National Science Foundation.  The findings and conclusions in this article have not been formally disseminated by the U.S. Department of Health \& Human Services nor by the U.S. Department of Energy, and should not be construed to represent any determination or policy of University, Agency, Administration and National Laboratory.

This manual may be incorrect or out-of-date.  The authors assume no responsibility for errors or omissions, or for damages resulting from the use of the information contained herein.





# References
<script language="JavaScript" src="include/headers.js"></script>
